name: dorm_fix
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0
workspace:
  - packages/ui_kit

environment:
  sdk: '>=3.12.0-221.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter  
    
  # UI Kit
  ui_kit:
    path: packages/ui_kit

  # Internationalization and localization support
  intl: ^0.20.2
  # BLoC
  flutter_bloc: ^9.1.1
  bloc_concurrency: ^0.3.0
  # Route
  auto_route: ^10.1.2
  # Firebase
  firebase_auth: ^6.4.0
  firebase_core: ^4.7.0
  # Google sign in
  google_sign_in: ^7.2.0
  # Logs
  logger: ^2.7.0
  # RX
  rxdart: ^0.28.0
  # Http clients  
  http: ^1.6.0
  # Local storage
  shared_preferences: ^2.5.5
  # Image picker
  image_picker: ^1.2.2
  video_player: ^2.11.1
  mime: ^2.0.0
  # Animations
  animations: ^2.2.0
  # DotEnv
  flutter_dotenv: ^6.0.0
  # Yandex MapKit
  yandex_mapkit: ^4.2.1
  supabase_flutter: ^2.12.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - .env
    - packages/ui_kit/assets/icons/

  fonts:
    - family: SF Pro
      fonts:
        - asset: packages/ui_kit/lib/fonts/SF-Pro-Display-Regular.otf
          weight: 400
        - asset: packages/ui_kit/lib/fonts/SF-Pro-Display-Semibold.otf
          weight: 600

    - family: UiIcons
      fonts:
        - asset: packages/ui_kit/lib/fonts/Icons.ttf